// front_react/src/components/contents/Paginate.js
import React, { Component } from 'react';

export default class Paginate extends Component {

    change = (event) => {
        this.props.changePage(+event.target.innerText);
    }

    next = () => {
        const { paginate } = this.props;
        let page = paginate.current_page + 1;

        if (page > paginate.last_page) page = paginate.last_page;
        this.props.changePage(page);
    }

    previous = () => {
        const { paginate } = this.props;
        let page = paginate.current_page - 1;

        if (page < 1) page = 1;
        this.props.changePage(page);
    }

    render() {
        const { paginate } = this.props;

        return (
            <div>
                <ul className="pagination justify-content-center">
                    <li className="page-item"><span className="page-link" style={{ cursor: "pointer" }} onClick={this.previous}> &lt; </span></li>
                    {[...Array(paginate.last_page)].map((x, i) =>
                        <li className={paginate.current_page === (i + 1) ? "page-item active" : "page-item"}
                            key={i} style={{ cursor: "pointer" }} >
                            <span className="page-link" onClick={this.change}>{i + 1}</span>
                        </li>
                    )}
                    <li className="page-item" style={{ cursor: "pointer" }} ><span className="page-link" onClick={this.next}> &gt; </span></li>
                </ul>
            </div>
        )
    }
}

// front/src/components/paginate.vue
<template>
	<div>
		<ul class="pagination justify-content-center" v-show="showPagination">
			<li class="page-item"><a class="page-link" @click.prevent="previous()" href=""> &lt; </a></li>

            <li v-for="item in this.pages" :key="item" :class="{'page-item active':item == current_page, 'page-item':item != current_page }">
                <a class="page-link" @click.prevent="changePage(item)" href="">{{item}}</a>
            </li>

			<li class="page-item"><a class="page-link" @click.prevent="next()" href=""> &gt; </a></li>
		</ul>
	</div>    
</template>

<script>

import { mapState, mapGetters, mapActions } from 'vuex';

export default {
     name: 'Paginate',
     data(){
         return {
            pages: []
         }
     },
    computed: mapState({
        ...mapGetters('paginate', ['paginate', 'current_page']),
        showPagination: function(){
            if( this.pages.length > 1) return true;

            return false;
        }
    }),
    watch: {
        paginate() {
            this.pages = [];
            for(let i=1; i <= this.paginate.last_page; i++){
                this.pages.push(i);
            }            
        }
    },
    methods: {
        ...mapActions('paginate', ['changePage']),
        previous() {
            let page = this.current_page - 1;
            if(page < 1) page = 1;
            this.changePage(page);
        },
        next() {
            let page = this.current_page + 1;
            if(page > this.paginate.last_page) page = this.paginate.last_page;
            this.changePage(page);
        }

     }
    
    
}
</script>

<style scoped>

</style>
