// front/src/views/imoveis/index.vue
<template>
  <div class="container-fluid">	
    <div class="py-5 text-center">
      <h2>Imóveis</h2>
    </div>
	<div class="row">
		<div class="col-sm-12">			
			<router-link to="/imoveis/cadastro" class="btn btn-success mb-3">Cadastrar</router-link>
		</div>
		<div class="col-sm-12">			
			<Dialog 
				v-if="isVisibleDialog" 
				@show="showDialog"
				:callback="this.callback"
				:title="'Deseja excluir o imóvel ?'"				
			/>
			<Table 
				:data="this.table" 
				:items="this.imoveis.result"				
				@list="list"
				@confirmDelete="confirmDelete"								
			/>
		</div>		
	</div>	
	<Snackbar ref='msgComponent' />
  </div>
</template>

<script>
import { mapState, mapGetters, mapActions } from 'vuex';
import Dialog from '@/components/dialog';
import Snackbar from '@/components/snackbar';
import Table from '@/components/table';

export default {
	name: "Imoveis",	
	components: {
		Dialog,
		Table,
		Snackbar		
	},
    props: {
		msg: String,
	},
	data: function(){
		return {
			table: {
				columns: [
					{
						name: 'E-mail',
						mapping: 'email',
						sort: true
					},
					{
						name: 'Cidade',
						mapping: 'cidade',
						sort: false
					},
					{
						name: 'Bairro',
						mapping: 'bairro',
						sort: false
					}
				]				
			},
			order: false,
			isVisibleDialog: false,
			callback: Function,
			id: null,
			queryString: ''
		}
	},

    created() {		
		this.$store.state.imovel.imoveis = {};		
		this.list();
	},

    computed: mapState({
		...mapGetters('imovel', ['imoveis','action', 'imovel']),
        contrato: function(){
            return this.imoveis.result.map(item =>{
				if(item.contrato){
					return 'Contratado';
				}
				
				return 'Não contratado';
			})
		}
	}),
	methods: {
		...mapActions('imovel', ['list']),
        showMessage: function(msg, bg) {            
            this.$refs.msgComponent.show({
                msg: msg,
                bgcolor: bg  // parametro opcional                
            })            
        },		

		remove(){
			this.$store.dispatch('imovel/remove', this.id);
		},

		confirmDelete(imovel){			
			this.showDialog(true);
			this.id = imovel.id;
			this.callback = this.remove;
		},
		
		showDialog(state){
			this.isVisibleDialog = state;
		}
	

	},
    watch: {
		imovel() {
			if(this.action == 'delete'){
				if(this.imovel.status){
					this.showMessage('Imóvel removido com sucesso!', 'success');					
					this.list();
				}else{
					this.showMessage('Ocorreu um erro!', 'danger');					
				}
			}
		}		
	}		
};
</script>

<style scoped>
</style>

// front_react/src/pages/Imoveis.js
// import { useEffect, useState } from "react";
import React, { Component } from 'react';
import { BrowserRouter as Router } from 'react-router-dom';
import { Link } from "react-router-dom";
import Table from '../components/Table';
import {table} from '../config/imoveis.config'
import api from '../api/apiImovel';
import Dialog from '../components/Dialog';
import Toastr from '../components/Toastr';

export default class Imoveis extends Component {
    constructor(props){
        super(props);
        this.state = {
            id: 0,
            data: '',
            errors: '',
            queryString: {
                page: 1,
                limit: 10
            },
            paginate: {
                current_page: 0,
                last_page: 0
            },
            table: table
        }        
    }
    
    componentDidMount() {
        this.list()
    }

    setPage = async (page) => {
        this.state.queryString.page = page;
    }

    changePage = (page) => {
        this.setPage(page);
        this.list();
    }

    /** prompt remove item */
    confirmDelete = (id) => {
        this.setState({id: id})
        this.dialog.show()
    }
  
     /** function called by the callback remove */
    remove = async () => {
        try {
            const request = await api.delete(this.state.id);
            if(request.status) {
                this.showMessage('Imóvel removido com sucesso!', 'success');
            } else {
                this.showMessage('Ocorreu um erro!', 'danger');	
            }

        } catch (error) {
            this.showMessage('Ocorreu um erro!', 'danger');
        }
    }

    /** prompt messsage after any action */
    showMessage = async (msg, bg) => {
        await this.toastr.show(msg, bg);
    }    

    /** callback function after delete */
    callback = () => {
        new Promise(function(resolve){resolve()})
        .then( this.setPage(1))
        .then( this.list() )
    }    

    list = async () => {
        const { page, limit } = this.state.queryString;
        const request = await api.List(`page=${page}&limit=${limit}`);
        this.setState({
            items: request.result,
            paginate:{
                current_page: request.paginate.current_page,
                last_page: request.paginate.last_page
            }
        })
    }    

    render() {
        const { items, table, paginate } = this.state;

        return (
            <div className="container">
                <Dialog
                    callback={this.remove}
                    onRef={ref => (this.dialog = ref)}
                 />
                 <Toastr
                    callback={this.callback}
                    onRef={ref => (this.toastr = ref)}
                 />
                <div className="py-5 text-center">
                    <h2>Imóveis</h2>
                </div>
                <div className="row">
                    <Router>
                    <div className="col-sm-12">
                        <Link className="btn btn-success mb-3" to="/imoveis/cadastro">Cadastrar</Link>
                    </div>
                    </Router>
                    <div className="col-sm-12">
                        <div className="table-responsive">
                        { items && <Table 
                                    table={table}
                                    items={items}                                    
                                    confirmDelete={ this.confirmDelete }
                                    changePage={ this.changePage }
                                    paginate={ paginate }
                                />
                        }
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}
