// front_react/src/App.js
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import Imoveis from './pages/Imoveis';
import Contratos from './pages/Contratos';
import 'bootstrap/dist/css/bootstrap.css';

import { Link } from "react-router-dom";

function App() {
  return (
    <div id="wrapper">
        <Router>
        <header>
            <ul className="nav justify-content-center">
                <li className="nav-item">
                    <Link className="nav-link" to="/">Imóveis</Link>
                </li>
                <li className="nav-item">
                    <Link className="nav-link" to="/contratos">Contratos</Link>                    
                </li>
            </ul>
        </header>
        <main role="main">
                <Switch>
                    <Route exact path="/" component={Imoveis} />
                    <Route exact path="/contratos" component={Contratos} />
                </Switch>
            <footer className="container">
                <p>2017-2020 Company, Inc. Privacy Terms</p>
            </footer>
        </main>
        </Router>
    </div>
  );
}

export default App;

// front/src/App.vue
<template>
    <div id="wrapper">
        <header>
            <ul class="nav justify-content-center">                
                <li class="nav-item">                    
                    <router-link class="nav-link" to="/">Imóveis</router-link>
                </li>
                <li class="nav-item">                    
                    <router-link class="nav-link" to="/contratos">Contratos</router-link>
                </li>
            </ul>
        </header>
        <main role="main">
            <div class="container">
                <router-view />
            </div>
            <footer class="container">                
                <p>© 2017-2020 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
            </footer>            
        </main>
    </div>
</template>

<style lang="scss">
  @import 'assets/css/app.scss';
</style>
